title: "My Portfolio"
description: "WordPress Web Designer, Automation Specialist, Funneler"
baseurl: "" # si es tuusuario.github.io deja vacío
url: "https://alixaizul.github.io"
theme: minima  # tema oficial sencillo

# Activar links de navegación desde /_data/navigation.yml
header_pages:
  - about.md
  - projects.md
